select * from Estudiante
CREATE TABLE Estudiante (
    ID INT PRIMARY KEY IDENTITY,
    DNI NVARCHAR(50) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDOS NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL,
    image VARBINARY(MAX) NULL
);
